#.streamlit/secrets.toml
[connections.snowflake]
account = "xxxxxxx-xxxxxxx"
user = "xxx"
password = "xxx"
role = "xxx"
warehouse = "xxx"
database = "xxx"
schema = "xxx"
client_session_keep_alive = true
